apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  hostPath:
     path: /data/mongo-prod/
status: {}
